### ISSUE TITLE
I think ,Honor Hunter v700 is not so gooooood.

### ISSUE THREAD

**Issue by amadeus233** [AceDroidX/HuaweiBatteryControl#2]
In the past two years, the motherboard of this model of my computer has broken down several times

**Comment by AceDroidX** [comment]
You are right, but Genshin Impact is a new open world adventure game independently developed by Mihoyo. The game takes place in a fantasy world called 'Tivat', where the chosen person is granted the 'Eye of God' to guide the power of the elements. You will play a mysterious role called "Traveler", who will meet friends with different personalities and unique abilities in the free travel, defeat strong enemies with them, and find lost relatives - at the same time, gradually discover the truth of "Genshin Impact".

**Comment by amadeus233** [comment]
屌
