### ISSUE TITLE
maybe it does not work in higner bios versions

### ISSUE THREAD

**Issue by huklers** [AceDroidX/HuaweiBatteryControl#3]
It does not work on my huawei pc, and I guess the reason is that I updated the bios before.
There is a similar issues in Huawei-WMI (you mentioned in your blog) about it.
Perhaps Huawei modified the input parameters in a higher bios version.
see : https://github.com/aymanbagabas/Huawei-WMI/issues/55

**Comment by AceDroidX** [comment]
What is the result of running the program? Is it `u8Output:0` or `u8Output:1`?
Can you provide the model and BIOS version of the device you are using?

Try this [HuaweiBatteryControl-x64.zip](https://github.com/AceDroidX/HuaweiBatteryControl/files/12901371/HuaweiBatteryControl-x64.zip)

This version is based on https://github.com/aymanbagabas/Huawei-WMI/issues/55#issuecomment-1028953673
and change the default value from 0x46281003 to 0x462848011503
Send me the results. Thanks!

**Comment by huklers** [comment]
Thanks for your reply.
After reading https://github.com/aymanbagabas/Huawei-WMI/issues/55 and your project again,
I try to adjust the 0x462848011503 to 77138820666627 (decimal) and it works on my huawei matebook D14 (bios 1.17)

> HuaweiBatteryControl-x64.exe 77138820666627

Command-line arguments:
  argv[0]   D:\Downloads\HuaweiBatteryControl-x64.exe
  argv[1]   77138820666627
data:77138820666627(0x462848011503)
Connected to ROOT\WMI WMI namespace
u8Output:0

and I try the previous version, it show:
data:4294967295(0xffffffff)
Connected to ROOT\WMI WMI namespace
u8Output:1

I notice that The max value is 4294967295(0xffffffff). 
And It looks like this little problem has been discovered and sloved by you.

**Comment by AceDroidX** [comment]
Thanks for testing!
Version 1.1 has been released
